Repository sdv-dev/SDV, pull requests merged in 2019-02, with the labels that each got.

#84 Issue 51: anonymize data
  docs/usage.rst
  examples/data_anonymization/Anonymization example.ipynb
  sdv/data_navigator.py
  sdv/sampler.py
  setup.py
  tests/sdv/test_data_navigator.py
Labels: new feature

#80 Issue 68: Add support for Vine Copulas as a Modeler, different distributions for Gaussian Copula.
  README.md
  sdv/modeler.py
  sdv/sampler.py
  tests/sdv/test_modeler.py
  tests/sdv/test_sampler.py
Labels: internal improvements, new feature

#90 Issue 89: Modeler.flatten_dict will flatten distributions regardless of their name
  sdv/modeler.py
  tests/sdv/test_modeler.py
Labels: internal improvements

#87 Issue 81: enforce sampled values in range [0,1] for categorical columns
  sdv/modeler.py
  sdv/sampler.py
  tests/sdv/test_modeler.py
  tests/sdv/test_sampler.py
Labels: internal improvements

#94 * fixes #92 converted Table to a namedtuple
  sdv/data_navigator.py
  setup.py
Labels: internal improvements
